name: flutter_application_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  anim_search_bar: ^2.0.3
  animated_text_kit: ^4.2.2
  auto_animated: ^3.2.0
  cloud_firestore: ^4.9.2
  custom_refresh_indicator: ^3.0.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  html: ^0.15.4
  html_unescape: ^2.0.0
  http: ^0.13.6
  intro_slider: ^4.2.1
  url_launcher: ^6.2.2
  video_player: ^2.8.1
  video_thumbnail: ^0.5.3
  xml: ^6.3.0
  youtube_api: ^1.0.4
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - Assets/Images/